version: '3.8'
services:

  danmu-auth-api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: final
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    networks:
      - danmu-auth

  postgres:
    image: bitnami/postgresql:15
    restart: always
    environment:
      - POSTGRESQL_USERNAME=leaperone
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=danmuauth_db
      - POSTGRESQL_POSTGRES_PASSWORD=password
      - POSTGRESQL_TIMEZONE=Asia/Shanghai
      - POSTGRESQL_LOG_TIMEZONE=Asia/Shanghai
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - danmu-auth

networks:
  danmu-auth:
    driver: bridge

volumes:
  postgres-data:
